builds:
  - id: goskills-runner
    binary: goskills
    main: ./cmd/skill-runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64